{"CreateTime": "2024-04-19 16:52:04", "filename": "Assert.py", "line": "51", "levelname": "ERROR", "message": "登录接口-全部参数正确,执行失败！实际响应码为：500,预期响应码为：200"}
{"CreateTime": "2024-04-19 16:59:40", "filename": "Assert.py", "line": "17", "levelname": "ERROR", "message": "testcae1,执行失败！实际响应结果为：7200,预期结果为：0"}
{"CreateTime": "2024-04-19 16:59:55", "filename": "Assert.py", "line": "17", "levelname": "ERROR", "message": "testcae1,执行失败！实际响应结果为：7200,预期结果为：7200"}
{"CreateTime": "2024-04-19 17:00:23", "filename": "Assert.py", "line": "17", "levelname": "ERROR", "message": "testcae1,执行失败！实际响应结果为：7200,预期结果为：7200"}
{"CreateTime": "2024-04-19 17:02:36", "filename": "Assert.py", "line": "17", "levelname": "ERROR", "message": "testcae1,执行失败！实际响应结果为：7200,预期结果为：0"}
{"CreateTime": "2024-04-19 17:08:40", "filename": "Assert.py", "line": "37", "levelname": "ERROR", "message": "测试用例1,执行失败！实际响应结果中不包含：expires_in222,实际结果为：{"access_token": "79_VVTxNDjBgbl_XYIn0tLRAxnXBpHdmxRqf81YQ7VqDcJpVi-SC-7C6l6Nr1ZA8qx48m6_2TEBPhq-RnpLxJWzq9ApNyN0ykxQZyItTjRLDcOrRkqSEWz9RJtlu5YYHXiACAIRH", "expires_in": 7200}"}
