{"name": "test_upload_kf_headImg[args5]", "status": "passed", "steps": [{"name": "执行接口", "status": "passed", "steps": [{"name": "响应体断言", "status": "passed", "steps": [{"name": "验证errcode是否与预期结果一致", "status": "passed", "start": 1715834334878, "stop": 1715834334878}, {"name": "验证errmsg是否与预期结果一致", "status": "passed", "start": 1715834334878, "stop": 1715834334878}], "start": 1715834334878, "stop": 1715834334878}], "start": 1715834334132, "stop": 1715834334878}], "attachments": [{"name": "log", "source": "2f77672a-6bb8-419c-85a6-598a668b8862-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "args", "value": "{'caseName': '【上传客服头像接口】用例6：无效的客服账号', 'method': 'post', 'url': '/customservice/kfaccount/uploadheadimg', 'params': {'kf_account': '无效的客服账号'}, 'files': {'media': 'tx3.png'}, 'excepted': {'errcode': 65401, 'errmsg': 'invalid custom service account', 'statusCode': 200}}"}], "start": 1715834334127, "stop": 1715834334886, "uuid": "98d2d5a1-5d7a-492f-b60d-74be33f30b02", "historyId": "d4050282f37a0ba1c8930f0d97921e1a", "testCaseId": "fc7f05464759ba910db9b356ad98205d", "fullName": "testcase.kf_mannage.test_upload_headImg.Test_kf#test_upload_kf_headImg", "labels": [{"name": "feature", "value": "客服管理模块"}, {"name": "epic", "value": "微信项目"}, {"name": "story", "value": "上传客服头像接口"}, {"name": "parentSuite", "value": "testcase.kf_mannage"}, {"name": "suite", "value": "test_upload_headImg"}, {"name": "subSuite", "value": "Test_kf"}, {"name": "host", "value": "DESKTOP-IG8PJM0"}, {"name": "thread", "value": "4692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.kf_mannage.test_upload_headImg"}]}